---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: spring-petclinic
spec:
  ports:
  - name: "entry-point"
    port: 80
    targetPort: 8080
    nodePort: 32001
  selector:
    app: api-gateway
  type: NodePort
